import EditableSections from "@/app/components/EditableSections";
import Breadcrumbs from "@/app/components/breadcrumbs";

export const metadata = { title: "Biofuels & Waste" };

const ROOT = "/dashboard/energy-carriers";

const DEFAULT_SECTIONS = [
    {
        id: "overview",
        label: "Overview",
        defaultContent: JSON.stringify([
            { type: "title", title: "Biofuels & Waste", subtitle: "Solid biomass, liquid biofuels, biogas, and waste-to-energy in South Africa" },
            "Biofuels and waste-derived energy occupy a modest but meaningful share of South Africa's energy balance, dominated in practice by **solid biomass** — bagasse from sugar milling, wood and forestry residues, and fuelwood used in low-income households — rather than by liquid biofuels, which remain a small and slow-growing category despite a decade of policy attention.\n\nThe key feedstocks are sugarcane and maize (for bioethanol), soybean and canola (for biodiesel), forestry and sawmill residues and bagasse (for solid biomass and co-generation), and municipal and industrial waste streams (for biogas and waste-to-energy). Sasol, sugar millers, and the forestry sector are among the largest industrial players in this space, alongside a growing number of independent biogas developers.",
        ]),
    },
    {
        id: "feedstocks-technologies",
        label: "Feedstocks & Technologies",
        defaultContent: JSON.stringify([
            { type: "title", title: "Feedstocks & Technologies" },
            "**Sugarcane ethanol** is the most discussed liquid biofuel feedstock, given South Africa's established sugar industry, though commercial-scale fuel ethanol production for blending has been slow to materialise relative to policy targets. **Biodiesel** from soybean, canola, and sunflower is produced at a smaller scale, constrained by feedstock costs and competition with food markets.\n\n**Solid biomass** is the largest category by energy volume: bagasse (sugarcane fibre residue) is widely used for on-site combined heat and power at sugar mills, wood pellets and forestry residues serve both export markets and domestic industrial heating, and fuelwood remains a significant — if statistically under-measured — energy source in rural and low-income households.\n\n**Biogas** from anaerobic digestion of wastewater sludge, agricultural waste, and organic municipal waste is a smaller but growing category, typically used for on-site heat and power at treatment works, farms, and food-processing facilities rather than being injected into a gas grid.",
        ]),
    },
    {
        id: "blending-mandates",
        label: "Blending Mandates",
        defaultContent: JSON.stringify([
            { type: "title", title: "Blending Mandates" },
            "South Africa's **Biofuels Industrial Strategy** (first published in 2007) set indicative national blending targets — around 2% bioethanol in petrol and 5% biodiesel in diesel — intended to stimulate a domestic biofuels industry, support agricultural development, and reduce reliance on imported liquid fuels. Mandatory blending regulations under the **Department of Mineral Resources and Energy (DMRE)** were subsequently developed to give the targets regulatory teeth.\n\nIn practice, uptake has been considerably slower than the strategy envisioned. Persistent obstacles have included feedstock cost competitiveness against imported refined fuels, uncertainty over pricing support mechanisms for producers, limited investment in dedicated production facilities, and competing food-versus-fuel land-use considerations for maize and sugarcane. As a result, actual blended volumes have remained well below the strategy's original targets for most of the period since its introduction.",
        ]),
    },
    {
        id: "waste-to-energy",
        label: "Waste-to-Energy",
        defaultContent: JSON.stringify([
            { type: "title", title: "Waste-to-Energy" },
            "**Landfill gas recovery** projects capture methane generated by decomposing organic waste at municipal landfill sites, either flaring it to reduce greenhouse gas impact or using it to generate electricity — several major metros have implemented landfill gas-to-electricity projects at large disposal sites. **Municipal solid waste (MSW)** incineration for direct energy recovery remains rare in South Africa compared to some international markets, constrained by capital costs and waste composition.\n\n**Biogas from wastewater treatment works** is a more established application: many municipal and industrial wastewater treatment plants already capture digester gas for on-site heat and, in some cases, electricity generation, reducing both energy costs and the facility's own greenhouse gas footprint.\n\nThe regulatory framework for these waste-derived energy pathways falls primarily under the **National Environmental Management: Waste Act (NEMWA)**, which governs waste classification, disposal, and licensing requirements that any waste-to-energy project must navigate alongside the separate energy-generation licensing regime.",
        ]),
    },
    {
        id: "datasets",
        label: "Relevant Datasets",
        defaultContent: JSON.stringify([
            { type: "title", title: "Relevant Datasets" },
            "- **DMRE biofuels data** — blending mandate compliance and production statistics\n- **SANEDI biomass atlas** — mapped biomass resource availability by region and feedstock type\n- **Municipal waste statistics** — published by metros and the national Department of Forestry, Fisheries and the Environment\n- **National Energy Balance biomass data** — biomass and waste contribution within the broader NEB dataset (see National Energy Planning)",
        ]),
    },
];

export default function Page() {
    return (
        <div className="space-y-8">
            <Breadcrumbs items={[
                { label: "Energy Carriers", href: ROOT },
                { label: "Biofuels & Waste" },
            ]} />

            <div>
                <p className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-green-700">Energy Carriers</p>
                <h1 className="text-2xl font-bold text-slate-900">Biofuels &amp; Waste</h1>
                <p className="mt-2 text-sm text-slate-500">
                    Solid biomass, liquid biofuels, biogas, and waste-to-energy pathways in South Africa.
                </p>
            </div>

            <EditableSections
                pageKey="ec.biofuels-and-waste"
                defaultSections={DEFAULT_SECTIONS}
            />
        </div>
    );
}
